name: Lint Markdown

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          config: .github/.markdownlint-cli2.yaml
